/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZespolRouteImport } from './routes/zespol'
import { Route as WarsztatyRouteImport } from './routes/warsztaty'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProjektRouteImport } from './routes/projekt'
import { Route as ONasRouteImport } from './routes/o-nas'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as IndexRouteImport } from './routes/index'

const ZespolRoute = ZespolRouteImport.update({
  id: '/zespol',
  path: '/zespol',
  getParentRoute: () => rootRouteImport,
} as any)
const WarsztatyRoute = WarsztatyRouteImport.update({
  id: '/warsztaty',
  path: '/warsztaty',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjektRoute = ProjektRouteImport.update({
  id: '/projekt',
  path: '/projekt',
  getParentRoute: () => rootRouteImport,
} as any)
const ONasRoute = ONasRouteImport.update({
  id: '/o-nas',
  path: '/o-nas',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/o-nas': typeof ONasRoute
  '/projekt': typeof ProjektRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/warsztaty': typeof WarsztatyRoute
  '/zespol': typeof ZespolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/o-nas': typeof ONasRoute
  '/projekt': typeof ProjektRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/warsztaty': typeof WarsztatyRoute
  '/zespol': typeof ZespolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/o-nas': typeof ONasRoute
  '/projekt': typeof ProjektRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/warsztaty': typeof WarsztatyRoute
  '/zespol': typeof ZespolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kontakt'
    | '/o-nas'
    | '/projekt'
    | '/sitemap.xml'
    | '/warsztaty'
    | '/zespol'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kontakt'
    | '/o-nas'
    | '/projekt'
    | '/sitemap.xml'
    | '/warsztaty'
    | '/zespol'
  id:
    | '__root__'
    | '/'
    | '/kontakt'
    | '/o-nas'
    | '/projekt'
    | '/sitemap.xml'
    | '/warsztaty'
    | '/zespol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KontaktRoute: typeof KontaktRoute
  ONasRoute: typeof ONasRoute
  ProjektRoute: typeof ProjektRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WarsztatyRoute: typeof WarsztatyRoute
  ZespolRoute: typeof ZespolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zespol': {
      id: '/zespol'
      path: '/zespol'
      fullPath: '/zespol'
      preLoaderRoute: typeof ZespolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warsztaty': {
      id: '/warsztaty'
      path: '/warsztaty'
      fullPath: '/warsztaty'
      preLoaderRoute: typeof WarsztatyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projekt': {
      id: '/projekt'
      path: '/projekt'
      fullPath: '/projekt'
      preLoaderRoute: typeof ProjektRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-nas': {
      id: '/o-nas'
      path: '/o-nas'
      fullPath: '/o-nas'
      preLoaderRoute: typeof ONasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KontaktRoute: KontaktRoute,
  ONasRoute: ONasRoute,
  ProjektRoute: ProjektRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WarsztatyRoute: WarsztatyRoute,
  ZespolRoute: ZespolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
